// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/viniosilva/socialassistanceapi/internal/api (interfaces: AddressApi)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAddressApi is a mock of AddressApi interface.
type MockAddressApi struct {
	ctrl     *gomock.Controller
	recorder *MockAddressApiMockRecorder
}

// MockAddressApiMockRecorder is the mock recorder for MockAddressApi.
type MockAddressApiMockRecorder struct {
	mock *MockAddressApi
}

// NewMockAddressApi creates a new mock instance.
func NewMockAddressApi(ctrl *gomock.Controller) *MockAddressApi {
	mock := &MockAddressApi{ctrl: ctrl}
	mock.recorder = &MockAddressApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAddressApi) EXPECT() *MockAddressApiMockRecorder {
	return m.recorder
}

// Configure mocks base method.
func (m *MockAddressApi) Configure() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Configure")
}

// Configure indicates an expected call of Configure.
func (mr *MockAddressApiMockRecorder) Configure() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configure", reflect.TypeOf((*MockAddressApi)(nil).Configure))
}
