// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/viniosilva/socialassistanceapi/internal/service (interfaces: FamilyService)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	service "github.com/viniosilva/socialassistanceapi/internal/service"
)

// MockFamilyService is a mock of FamilyService interface.
type MockFamilyService struct {
	ctrl     *gomock.Controller
	recorder *MockFamilyServiceMockRecorder
}

// MockFamilyServiceMockRecorder is the mock recorder for MockFamilyService.
type MockFamilyServiceMockRecorder struct {
	mock *MockFamilyService
}

// NewMockFamilyService creates a new mock instance.
func NewMockFamilyService(ctrl *gomock.Controller) *MockFamilyService {
	mock := &MockFamilyService{ctrl: ctrl}
	mock.recorder = &MockFamilyServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFamilyService) EXPECT() *MockFamilyServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFamilyService) Create(arg0 context.Context, arg1 service.FamilyCreateDto) (service.FamilyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(service.FamilyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFamilyServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFamilyService)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockFamilyService) Delete(arg0 context.Context, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFamilyServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFamilyService)(nil).Delete), arg0, arg1)
}

// FindAll mocks base method.
func (m *MockFamilyService) FindAll(arg0 context.Context) (service.FamiliesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].(service.FamiliesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockFamilyServiceMockRecorder) FindAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockFamilyService)(nil).FindAll), arg0)
}

// FindOneById mocks base method.
func (m *MockFamilyService) FindOneById(arg0 context.Context, arg1 int) (service.FamilyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneById", arg0, arg1)
	ret0, _ := ret[0].(service.FamilyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneById indicates an expected call of FindOneById.
func (mr *MockFamilyServiceMockRecorder) FindOneById(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneById", reflect.TypeOf((*MockFamilyService)(nil).FindOneById), arg0, arg1)
}

// Update mocks base method.
func (m *MockFamilyService) Update(arg0 context.Context, arg1 service.FamilyUpdateDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockFamilyServiceMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFamilyService)(nil).Update), arg0, arg1)
}
