// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/viniosilva/socialassistanceapi/internal/api (interfaces: FamilyApi)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFamilyApi is a mock of FamilyApi interface.
type MockFamilyApi struct {
	ctrl     *gomock.Controller
	recorder *MockFamilyApiMockRecorder
}

// MockFamilyApiMockRecorder is the mock recorder for MockFamilyApi.
type MockFamilyApiMockRecorder struct {
	mock *MockFamilyApi
}

// NewMockFamilyApi creates a new mock instance.
func NewMockFamilyApi(ctrl *gomock.Controller) *MockFamilyApi {
	mock := &MockFamilyApi{ctrl: ctrl}
	mock.recorder = &MockFamilyApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFamilyApi) EXPECT() *MockFamilyApiMockRecorder {
	return m.recorder
}

// Configure mocks base method.
func (m *MockFamilyApi) Configure() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Configure")
}

// Configure indicates an expected call of Configure.
func (mr *MockFamilyApiMockRecorder) Configure() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configure", reflect.TypeOf((*MockFamilyApi)(nil).Configure))
}
