// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/viniosilva/socialassistanceapi/internal/api (interfaces: ResourceToAddressApi)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockResourceToAddressApi is a mock of ResourceToAddressApi interface.
type MockResourceToAddressApi struct {
	ctrl     *gomock.Controller
	recorder *MockResourceToAddressApiMockRecorder
}

// MockResourceToAddressApiMockRecorder is the mock recorder for MockResourceToAddressApi.
type MockResourceToAddressApiMockRecorder struct {
	mock *MockResourceToAddressApi
}

// NewMockResourceToAddressApi creates a new mock instance.
func NewMockResourceToAddressApi(ctrl *gomock.Controller) *MockResourceToAddressApi {
	mock := &MockResourceToAddressApi{ctrl: ctrl}
	mock.recorder = &MockResourceToAddressApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceToAddressApi) EXPECT() *MockResourceToAddressApiMockRecorder {
	return m.recorder
}

// Configure mocks base method.
func (m *MockResourceToAddressApi) Configure() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Configure")
}

// Configure indicates an expected call of Configure.
func (mr *MockResourceToAddressApiMockRecorder) Configure() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configure", reflect.TypeOf((*MockResourceToAddressApi)(nil).Configure))
}
