definitions:
  api.HttpError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: invalid parameter
        type: string
    type: object
  service.Address:
    properties:
      city:
        example: São Paulo
        type: string
      complement:
        example: 1A
        type: string
      country:
        example: BR
        type: string
      created_at:
        example: 2000-01-01T12:03:00
        type: string
      deleted_at:
        example: 2000-01-01T12:03:00
        type: string
      id:
        example: 1
        type: integer
      neighborhood:
        example: Centro Histórico
        type: string
      number:
        example: "1000"
        type: string
      state:
        example: SP
        type: string
      street:
        example: R. Vinte e Cinco de Março
        type: string
      updated_at:
        example: 2000-01-01T12:03:00
        type: string
      zipcode:
        example: "01021100"
        type: string
    type: object
  service.AddressDto:
    properties:
      city:
        example: São Paulo
        type: string
      complement:
        example: 1A
        type: string
      country:
        example: BR
        type: string
      neighborhood:
        example: Centro Histórico
        type: string
      number:
        example: "1000"
        type: string
      state:
        example: SP
        type: string
      street:
        example: R. Vinte e Cinco de Março
        type: string
      zipcode:
        example: "01021100"
        type: string
    required:
    - city
    - complement
    - country
    - neighborhood
    - number
    - state
    - street
    - zipcode
    type: object
  service.AddressResponse:
    properties:
      data:
        $ref: '#/definitions/service.Address'
    type: object
  service.AddressesResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/service.Address'
        type: array
    type: object
  service.Person:
    properties:
      created_at:
        example: 2000-01-01T12:03:00
        type: string
      deleted_at:
        example: 2000-01-01T12:03:00
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Cláudio
        type: string
      updated_at:
        example: 2000-01-01T12:03:00
        type: string
    type: object
  service.PersonDto:
    properties:
      name:
        example: Cláudio
        type: string
    required:
    - name
    type: object
  service.PersonResponse:
    properties:
      data:
        $ref: '#/definitions/service.Person'
    type: object
  service.PersonsResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/service.Person'
        type: array
    type: object
  service.Resource:
    properties:
      amount:
        example: 5
        type: number
      created_at:
        example: 2000-01-01T12:03:00
        type: string
      deleted_at:
        example: ""
        type: string
      id:
        example: 1
        type: integer
      measurement:
        example: Kg
        type: string
      name_at:
        example: Arroz
        type: string
      updated_at:
        example: 2000-01-01T12:03:00
        type: string
    type: object
  service.ResourceDto:
    properties:
      amount:
        example: 5
        type: number
      measurement:
        example: Kg
        type: string
      name_at:
        example: Arroz
        type: string
    required:
    - amount
    - measurement
    - name_at
    type: object
  service.ResourceResponse:
    properties:
      data:
        $ref: '#/definitions/service.Resource'
    type: object
  service.ResourcesResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/service.Resource'
        type: array
    type: object
info:
  contact: {}
paths:
  /api/v1/addresses:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.AddressesResponse'
      summary: find all addresses
      tags:
      - address
    post:
      consumes:
      - application/json
      parameters:
      - description: Create address
        in: body
        name: address
        required: true
        schema:
          $ref: '#/definitions/service.AddressDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/service.AddressResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.HttpError'
      summary: create an address
      tags:
      - address
  /api/v1/addresses/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: address ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.HttpError'
      summary: delete an address
      tags:
      - address
    get:
      consumes:
      - application/json
      parameters:
      - description: address ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.AddressesResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.HttpError'
      summary: find address by id
      tags:
      - address
    patch:
      consumes:
      - application/json
      parameters:
      - description: address ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update address
        in: body
        name: address
        required: true
        schema:
          $ref: '#/definitions/service.AddressDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.AddressResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.HttpError'
      summary: update an address
      tags:
      - address
  /api/v1/persons:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.PersonResponse'
      summary: find all persons
      tags:
      - person
    post:
      consumes:
      - application/json
      parameters:
      - description: Create person
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/service.PersonDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/service.PersonResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.HttpError'
      summary: create a person
      tags:
      - person
  /api/v1/persons/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: person ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.HttpError'
      summary: delete a person
      tags:
      - person
    get:
      consumes:
      - application/json
      parameters:
      - description: person ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.PersonsResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.HttpError'
      summary: find person by id
      tags:
      - person
    patch:
      consumes:
      - application/json
      parameters:
      - description: person ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update person
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/service.PersonDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.PersonResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.HttpError'
      summary: update a person
      tags:
      - person
  /api/v1/resources:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.ResourceResponse'
      summary: find resource by id
      tags:
      - resource
    post:
      consumes:
      - application/json
      parameters:
      - description: Create resource
        in: body
        name: resource
        required: true
        schema:
          $ref: '#/definitions/service.ResourceDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/service.ResourceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.HttpError'
      summary: create a resource
      tags:
      - resource
  /api/v1/resources/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: resource ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.HttpError'
      summary: delete a resource
      tags:
      - resource
    patch:
      consumes:
      - application/json
      parameters:
      - description: resource ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update resource
        in: body
        name: resource
        required: true
        schema:
          $ref: '#/definitions/service.ResourceDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.ResourceResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.HttpError'
      summary: update a resource
      tags:
      - resource
swagger: "2.0"
