definitions:
  api.HttpError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: invalid parameter
        type: string
    type: object
  service.PeopleResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/service.Person'
        type: array
    type: object
  service.Person:
    properties:
      created_at:
        example: 2000-01-01T12:03:00
        type: string
      deleted_at:
        example: 2000-01-01T12:03:00
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Cláudio
        type: string
      updated_at:
        example: 2000-01-01T12:03:00
        type: string
    type: object
  service.PersonDto:
    properties:
      name:
        example: Cláudio
        type: string
    required:
    - name
    type: object
  service.PersonResponse:
    properties:
      data:
        $ref: '#/definitions/service.Person'
    type: object
info:
  contact: {}
paths:
  /api/v1/people:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.PeopleResponse'
      summary: find all people
      tags:
      - person
    post:
      consumes:
      - application/json
      parameters:
      - description: Create person
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/service.PersonDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/service.PersonResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.HttpError'
      summary: create a person
      tags:
      - person
  /api/v1/people/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: person ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.PersonResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.HttpError'
      summary: delete a person
      tags:
      - person
    get:
      consumes:
      - application/json
      parameters:
      - description: person ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.PeopleResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.HttpError'
      summary: find person by id
      tags:
      - person
    patch:
      consumes:
      - application/json
      parameters:
      - description: person ID
        in: path
        name: id
        required: true
        type: integer
      - description: Update person
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/service.PersonDto'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/service.PersonResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.HttpError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.HttpError'
      summary: update a person
      tags:
      - person
swagger: "2.0"
